// Category
export const CATEGORY_API_LOAD = 'CATEGORY_API_LOAD'
export const CATEGORY_API_SAVE = 'CATEGORY_API_SAVE'
export const CATEGORY_FORM_UPDATE = 'CATEGORY_FORM_UPDATE'
export const CATEGORY_FIND = 'CATEGORY_FIND'
export const CATEGORY_API_DELETE = 'CATEGORY_API_DELETE'
