// User
export const SET_ROLES = 'SET_ROLES'

// Category
export const SET_CATEGORY_LIST = 'SET_CATEGORY_LIST '
export const SET_CATEGORY_DIALOG_FORM_VISIBLE = 'SET_CATEGORY_DIALOG_FORM_VISIBLE'
export const SET_CATEGORY_FORM_DATA = 'SET_CATEGORY_FORM_DATA'
export const SET_CATEGORY_FORM_ERROR = 'SET_CATEGORY_FORM_ERROR'

// Product
export const SET_PRODUCT_LIST = 'SET_PRODUCT_LIST'
export const SET_PRODUCT_TOTAL = 'SET_PRODUCT_TOTAL'
